Defining Parameters
T = 4 ; 
Sample_Time = 0.01;
t = [0:Sample_Time:T];
F_1 = 1;
F_2 = 20;
F_3 = 10;

Signal Design
Sig_1 = sin(2*pi*F_1*t);
Sig_2 = cos(2*pi*F_2*t);
Sig_3 = sin(2*pi*F_3*t);

Random Noise
Noise = rand(1,length(t));

HAVE A LOOK AT THE GENERAED SIGNALS
plot(t,Sig_1,"r");
xlabel("Time");
ylabel("Magnitude");
hold on
plot(t,Sig_2,"g");
plot(t,Sig_3,"b");
legend("Sig_1","Sig_2","Sig_3");
shg

%Let's Combine Them with random weights

Combined_Signal = 3*Sig_1 + 2*Sig_2 + Sig_3 +Noise;
Combined_Signal = Combined_Signal + 4*Noise;
plot(t,Combined_Signal);

%Lets test Out our hypothesis Using Fourier Transform!

Fourier_Matrix = fft(Combined_Signal);
plot(abs(Fourier_Matrix),"r");

%abs Function will give you the value of every seriel complex number
%generated by the fourier transforms
%Make a Frequency_array to have a better idea of diversity of signal

Frequency_Domain = (1/T)*[1:length(Combined_Signal)];

%Let's Plot it again

plot(Frequency_Domain,abs(Fourier_Matrix),"r");
xlabel("Frequency(Hz)");

%Now From the Fourier Curve We HAVE THREE Frequencies in Consideration
%1.25,10.25,20.25

%lets Try to filter them
filterDesigner

%Now We Will be using convulution to have the filtered output

Filtered_Low = conv(Impulse_Response,Combined_Signal);
Filtered_Low = Filtered_Low(30:430);

%I cut it back so that i have same number of serial in the y and x axis
plot(t,Filtered_Low)

%Fantastic_We Finally Have our System Signal

%But THERE is Too Much Noise
%A small trick a of adding a moving average filter may work
Filtered_Low_NM = Filtered_Low;
Filtered_Low = movmean(Filtered_Low,10);
plot(Filtered_Low);

% %let's Recap
% subplot(3,2,1);
% plot(t,Sig_1,"r");
% hold on
% plot(t,Sig_2,"c");
% hold on
% plot(t,Sig_3,"b");
% hold on
% plot(t,Noise,"k");
% legend("Sig 1","Sig 2","Sig 3","Noise");
% title("Four Random Signals");
% xlabel("Time(s)");
% ylabel("Amplitude");
% 
% 
% subplot(3,2,2);
% plot(t,Combined_Signal,"b");
% title("Combined Signal");
% xlabel("Time(s)");
% ylabel("Amplitude");
% 
% subplot(3,2,3);
% plot(Frequency_Domain,abs(Fourier_Matrix),"r");
% title("FOURIER Absolute");
% xlabel("Frequency");
% ylabel("Amplitude");
% 
% subplot(3,2,4);
% plot(Impulse_Response,"c");
% title("Impulse Response Low Pass FILTER Fc = 1.25hz");
% xlabel("Samples");
% ylabel("Amplitude");
% 
% subplot(3,2,5);
% plot(t,Filtered_Low_NM,"r");
% title("Convoluted Signal(Very Noisy)");
% xlabel("Time(s)");
% ylabel("Amplitude");
% 
% subplot(3,2,6);
% plot(t,Filtered_Low,"b");
% title("Filtered using Moving AVERAGE");
% xlabel("Time(s)");
% ylabel("Amplitude");
% 
% suptitle("Signal Synthesis Using Fourier Transforms");